### ISSUE TITLE
After obfuscating runnable jars, it shows it has been compressed and nested jar files must be stored without compression.

### ISSUE THREAD

**Issue by wyw900807** [superblaubeere27/obfuscator#66] opened 2020-02-19 03:38 UTC
After obfuscating the runnable jars and inputing java -jar ****，the console outputs :
Exception in thread "main" java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/jul-to-slf4j-1.7.24.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(Unknown Source)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(Unknown Source)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(Unknown Source)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(Unknown Source)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(Unknown Source)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(Unknown Source)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(Unknown Source)
	at org.springframework.boot.loader.Launcher.launch(Unknown Source)
	at org.springframework.boot.loader.JarLauncher.main(Unknown Source)

But if I only obfuscate the .class file and use  jar c0fM to repackage it, this can work.

**Comment by ItzSomebody** [comment] 2020-02-19 06:03
Duplicate of #59 ?

**Closed** 2020-02-19 06:34 UTC
