### ISSUE TITLE
With GUI is working but with command give error

### ISSUE THREAD

**Issue by AskMeCode** [superblaubeere27/obfuscator#52] opened 2019-09-06 19:59 UTC
Hello dear
When i use obfuscator-gui is working good i build the same config to use it with command.
i use this command:
java -jar .\Obfuscator\obfuscator-193.jar --config .\Obfuscator\Conf.json --jarIn abc.jar --jarOut .\Temp\abc2.jar

but i have this error:

Loading classpath...
Reading input...
Building Hierarchy...
Finishing...
>>> Processing completed. If you found a bug / if the output
pen an issue at https://github.com/superblaubeere27/obfuscat
ERROR: java/lang/Object is missing in the classPath.
me.superblaubeere27.jobf.utils.MissingClassException: java/l
g in the classPath.
        at me.superblaubeere27.jobf.JObfImpl.buildHierarchy(
        at me.superblaubeere27.jobf.processors.name.NameObfu
t(NameObfuscation.java:62)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObf
        at me.superblaubeere27.jobf.JObf.main(JObf.java:231)

Can you give help please.

**Comment by cookiedragon234** [comment] 2019-09-08 11:42
Can you post the config contents? I'm guessing that you have not included
```
C:\\Program Files\\Java\\jre1.8.0_211\\lib
```
in the classpath (libraries section of config).

**Comment by superblaubeere27** [comment] 2019-09-08 11:55
@AskMeCode It is how @cookiedragon234, you foget to add the JRE Runtime libraries. You are using MacOSX, so the JDK is somewhere else. If you don't know how to find it: Here is the solution on StackOverflow https://stackoverflow.com/questions/18144660/what-is-path-of-jdk-on-mac.
You just have to add the `<JDK>/lib` Folder. You can check if it's the right folder by checking if `rt.jar` is in it. In the case you can't find it just answere, we will help you :D

**Comment by AskMeCode** [comment] 2019-09-08 22:10
Thank you for your answer but as i told you with interface-gui is working without any problem i have already add this C:\\Program Files\\Java\\jre1.8.0_201\\lib
also exist in the config file

**Comment by cookiedragon234** [comment] 2019-09-08 22:12
@AskMeCode can you post your config?

**Comment by AskMeCode** [comment] 2019-09-08 22:13
{
  "input": "C:\\Users\\said\\Desktop\\dex2jar-2.0\\abc_ori.jar",
  "output": "C:\\Users\\said\\Desktop\\dex2jar-2.0\\Temp\\abc.jar",
  "script": "function isRemappingEnabledForClass(node) {\n    return false;\n}\nfunction isObfuscatorEnabledForClass(node) {\n    return true;\n}",
  "libraries": [
    "C:\\Program Files\\Java\\jre1.8.0_201\\lib"
  ],
  "Crasher": {
    "Enabled": false
  },
  "InvokeDynamic": {
    "Enabled": false
  },
  "HWIDPRotection": {
    "Enabled": false,
    "HWID": "17BC92BE25B05F9D583AEDA89ED4906F"
  },
  "Optimizer": {
    "Enabled": false,
    "Replace String.equals()": false,
    "Replace String.equalsIgnoreCase()": false,
    "Optimize static string calls": false
  },
  "LineNumberRemover": {
    "Enabled": false,
    "Rename local variables": false,
    "Remove Line Numbers": true,
    "Remove Debug Names": true,
    "Add Local Variables": true,
    "New SourceFile Name": ""
  },
  "StringEncryption": {
    "Enabled": false,
    "HideStrings": false,
    "AES": false
  },
  "NumberObfuscation": {
    "Enabled": true,
    "Extract to Array": true,
    "Obfuscate Zero": true,
    "Shift": false,
    "And": false,
    "Multiple Instructions": true
  },
  "ReferenceProxy": {
    "Enabled": false
  },
  "ShuffleMembers": {
    "Enabled": true
  },
  "InnerClassRemover": {
    "Enabled": true,
    "Remap": false,
    "Remove Metadata": true
  },
  "NameObfuscation": {
    "Enabled": true
  },
  "Packager": {
    "Enabled": false,
    "Use MainClass from the JAR manifest": true,
    "Main class": "org.example.Main"
  },
  "FlowObfuscator": {
    "Enabled": true,
    "Mangle Comparisons": true,
    "Replace GOTO": true,
    "Replace If": true,
    "Bad POP": true,
    "Bad Concat": true,
    "Mangle Switches": false,
    "Mangle Return": false,
    "Mangle Local Variables": false
  },
  "HideMembers": {
    "Enabled": false
  },
  "Inlining": {
    "Enabled": false
  }
}

**Comment by cookiedragon234** [comment] 2019-09-08 22:16
Can you post the entire config with in a format as specified here https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks (`\`\`\`` on each side of the text)

**Comment by cookiedragon234** [comment] 2019-09-08 22:20
Ok, the issue is that file paths must have the directory delimiters ("\") escaped (making them "\\").

This is your current config:
```
{
	"input": "C:\Users\said\Desktop\dex2jar-2.0\abc_ori.jar",
	"output": "C:\Users\said\Desktop\dex2jar-2.0\Temp\abc.jar",
	"script": "function isRemappingEnabledForClass(node) {\n return false;\n}\nfunction isObfuscatorEnabledForClass(node) {\n return true;\n}",
	"libraries": [
		"C:\Program Files\Java\jre1.8.0_201\lib"
	],
	"Crasher": {
		"Enabled": false
	},
	"InvokeDynamic": {
		"Enabled": false
	},
	"HWIDPRotection": {
		"Enabled": false,
		"HWID": "17BC92BE25B05F9D583AEDA89ED4906F"
	},
	"Optimizer": {
		"Enabled": false,
		"Replace String.equals()": false,
		"Replace String.equalsIgnoreCase()": false,
		"Optimize static string calls": false
	},
	"LineNumberRemover": {
		"Enabled": false,
		"Rename local variables": false,
		"Remove Line Numbers": true,
		"Remove Debug Names": true,
		"Add Local Variables": true,
		"New SourceFile Name": ""
	},
	"StringEncryption": {
		"Enabled": false,
		"HideStrings": false,
		"AES": false
	},
	"NumberObfuscation": {
		"Enabled": true,
		"Extract to Array": true,
		"Obfuscate Zero": true,
		"Shift": false,
		"And": false,
		"Multiple Instructions": true
	},
	"ReferenceProxy": {
		"Enabled": false
	},
	"ShuffleMembers": {
		"Enabled": true
	},
	"InnerClassRemover": {
		"Enabled": true,
		"Remap": false,
		"Remove Metadata": true
	},
	"NameObfuscation": {
		"Enabled": true
	},
	"Packager": {
		"Enabled": false,
		"Use MainClass from the JAR manifest": true,
		"Main class": "org.example.Main"
	},
	"FlowObfuscator": {
		"Enabled": true,
		"Mangle Comparisons": true,
		"Replace GOTO": true,
		"Replace If": true,
		"Bad POP": true,
		"Bad Concat": true,
		"Mangle Switches": false,
		"Mangle Return": false,
		"Mangle Local Variables": false
	},
	"HideMembers": {
		"Enabled": false
	},
	"Inlining": {
		"Enabled": false
	}
}
```

so you need to change it to:
```
{
	"input": "C:\\Users\\said\\Desktop\\dex2jar-2.0\\abc_ori.jar",
	"output": "C:\\Users\\said\\Desktop\\dex2jar-2.0\\Temp\\abc.jar",
	"script": "function isRemappingEnabledForClass(node) {\n return false;\n}\nfunction isObfuscatorEnabledForClass(node) {\n return true;\n}",
	"libraries": [
		"C:\\Program Files\\Java\\jre1.8.0_201\\lib"
	],
	"Crasher": {
		"Enabled": false
	},
	"InvokeDynamic": {
		"Enabled": false
	},
	"HWIDPRotection": {
		"Enabled": false,
		"HWID": "17BC92BE25B05F9D583AEDA89ED4906F"
	},
	"Optimizer": {
		"Enabled": false,
		"Replace String.equals()": false,
		"Replace String.equalsIgnoreCase()": false,
		"Optimize static string calls": false
	},
	"LineNumberRemover": {
		"Enabled": false,
		"Rename local variables": false,
		"Remove Line Numbers": true,
		"Remove Debug Names": true,
		"Add Local Variables": true,
		"New SourceFile Name": ""
	},
	"StringEncryption": {
		"Enabled": false,
		"HideStrings": false,
		"AES": false
	},
	"NumberObfuscation": {
		"Enabled": true,
		"Extract to Array": true,
		"Obfuscate Zero": true,
		"Shift": false,
		"And": false,
		"Multiple Instructions": true
	},
	"ReferenceProxy": {
		"Enabled": false
	},
	"ShuffleMembers": {
		"Enabled": true
	},
	"InnerClassRemover": {
		"Enabled": true,
		"Remap": false,
		"Remove Metadata": true
	},
	"NameObfuscation": {
		"Enabled": true
	},
	"Packager": {
		"Enabled": false,
		"Use MainClass from the JAR manifest": true,
		"Main class": "org.example.Main"
	},
	"FlowObfuscator": {
		"Enabled": true,
		"Mangle Comparisons": true,
		"Replace GOTO": true,
		"Replace If": true,
		"Bad POP": true,
		"Bad Concat": true,
		"Mangle Switches": false,
		"Mangle Return": false,
		"Mangle Local Variables": false
	},
	"HideMembers": {
		"Enabled": false
	},
	"Inlining": {
		"Enabled": false
	}
}
```

**Comment by AskMeCode** [comment] 2019-09-08 22:26
sorry i have this "\\" i don't know why is messing when i past the code

**Comment by AskMeCode** [comment] 2019-09-08 22:27
``
{
  "input": "C:\\Users\\test\\Desktop\\dfile\\abc_ori.jar",
  "output": "C:\\Users\\test\\Desktop\\dfile\\Temp\\abc.jar",
  "script": "function isRemappingEnabledForClass(node) {\n    return false;\n}\nfunction isObfuscatorEnabledForClass(node) {\n    return true;\n}",
  "libraries": [
    "C:\\Program Files\\Java\\jre1.8.0_201\\lib"
  ],
  "Crasher": {
    "Enabled": false
  },
  "InvokeDynamic": {
    "Enabled": false
  },
  "HWIDPRotection": {
    "Enabled": false,
    "HWID": "17BC92BE25B05F9D583AEDA89ED4906F"
  },
  "Optimizer": {
    "Enabled": false,
    "Replace String.equals()": false,
    "Replace String.equalsIgnoreCase()": false,
    "Optimize static string calls": false
  },
  "LineNumberRemover": {
    "Enabled": false,
    "Rename local variables": false,
    "Remove Line Numbers": true,
    "Remove Debug Names": true,
    "Add Local Variables": true,
    "New SourceFile Name": ""
  },
  "StringEncryption": {
    "Enabled": false,
    "HideStrings": false,
    "AES": false
  },
  "NumberObfuscation": {
    "Enabled": true,
    "Extract to Array": true,
    "Obfuscate Zero": true,
    "Shift": false,
    "And": false,
    "Multiple Instructions": true
  },
  "ReferenceProxy": {
    "Enabled": false
  },
  "ShuffleMembers": {
    "Enabled": true
  },
  "InnerClassRemover": {
    "Enabled": true,
    "Remap": false,
    "Remove Metadata": true
  },
  "NameObfuscation": {
    "Enabled": true
  },
  "Packager": {
    "Enabled": false,
    "Use MainClass from the JAR manifest": true,
    "Main class": "org.example.Main"
  },
  "FlowObfuscator": {
    "Enabled": true,
    "Mangle Comparisons": true,
    "Replace GOTO": true,
    "Replace If": true,
    "Bad POP": true,
    "Bad Concat": true,
    "Mangle Switches": false,
    "Mangle Return": false,
    "Mangle Local Variables": false
  },
  "HideMembers": {
    "Enabled": false
  },
  "Inlining": {
    "Enabled": false
  }
}``

**Comment by cookiedragon234** [comment] 2019-09-08 22:31
Can you confirm that the directory is correct? If you go to it in file explorer it should look like this:
![Directory](https://i.imgur.com/1iqvrSJ.png)

**Comment by AskMeCode** [comment] 2019-09-08 22:35
yes i have check this i can send you screenshot also if you like

**Comment by cookiedragon234** [comment] 2019-09-08 22:38
If you open rt.jar in winrar and go to java/lang can you see Object.class?

![Object](https://i.imgur.com/9vrMMGT.png)

And does it also have the same file size?

**Comment by AskMeCode** [comment] 2019-09-08 22:38
But why with the interface is working good 
![image](https://user-images.githubusercontent.com/30801739/64495418-b1683c00-d291-11e9-838f-d94154edbc18.png)

**Comment by AskMeCode** [comment] 2019-09-08 22:40
> If you open rt.jar in winrar and go to java/lang can you see Object.class?
> 
> ![Object](https://camo.githubusercontent.com/b7d8010df9600a1dddd0fdb24268883787e73cf4/68747470733a2f2f692e696d6775722e636f6d2f3976724d4d47542e706e67)
> 
> And does it also have the same file size?

![image](https://user-images.githubusercontent.com/30801739/64495436-fdb37c00-d291-11e9-941a-5a1b9a99daf2.png)

**Comment by KingDeng** [comment] 2019-09-09 11:21
Is this issue fixed?I have the same error, I'm sure jre library path is correct, but always missing java/lang/Object

**Comment by superblaubeere27** [comment] 2019-09-09 18:41
@KingDeng can you run `tree` in the folder you specified and send us the results?

**Comment by KingDeng** [comment] 2019-09-10 02:14
@superblaubeere27 this is tree results:
![tree](https://user-images.githubusercontent.com/6926561/64578667-b4a71900-d3b2-11e9-82b9-54e3f193d211.jpg)
![image](https://user-images.githubusercontent.com/6926561/64578896-7eb66480-d3b3-11e9-929e-8295acfd3c7a.png)
this is my config:
![image](https://user-images.githubusercontent.com/6926561/64578730-e4562100-d3b2-11e9-8cb3-9b9af522f243.png)
I found some strange things, I have installed two jdks on company's pc,one 1.7,other 1.8, then obfuscator cmd and gui con't run; but I only installed a jdk on my private pc,  the gui can run, cmd con't run.

**Comment by superblaubeere27** [comment] 2019-09-13 10:53
Fixed in cfd6d9e

**Closed by superblaubeere27** 2019-09-13 10:53 UTC
Labels: bug, fixed, good first issue

**Comment by AskMeCode** [comment] 2019-09-13 10:57
Thanks dear @superblaubeere27 but were is the link to download 1.9.4 ?

**Comment by superblaubeere27** [comment] 2019-09-13 10:58
@AskMeCode Here is the latest build of JitPack: https://jitpack.io/com/github/superblaubeere27/obfuscator/obfuscator-core/8fb0fc2e37/obfuscator-core-8fb0fc2e37.jar

**Comment by AskMeCode** [comment] 2019-09-13 11:43
dear @superblaubeere27 can you help to add the function load config for the version 1.71 ? because this is the alone version work great for me without any crash in my app

**Comment by superblaubeere27** [comment] 2019-09-14 08:07
@AskMeCode In CLI? No. This is a newer feature. In GUI yes. This is fully supported in 1.7+. If there is a bug please report it so we can fix it :D

**Comment by a8underscore** [comment] 2020-04-15 19:05
I get this issue in gui @superblaubeere27  but not in command line

**Comment by liangmiQwQ** [comment] 2025-02-11 03:46
1.9.4 also do something error it will show "NoSuchFile" no matter libraries
